version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/model.json:/model.json  # add file in json.models
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
    