# Используем базовый образ, например, Alpine Linux
FROM alpine:latest

# Копируем файл JSON внутрь образа
COPY model.json /data/model.json

# Опционально: укажите каталог, где будет храниться файл JSON
WORKDIR /data
